version: "3"

services:
  backend:
    build: backend/
    restart: always
    container_name: backend

  frontend_and_nginx:
    build: frontend/
    restart: always
    container_name: frontend_and_nginx
    ports:
      - 0.0.0.0:8080:80
    links:
      - backend


  tg_bot:
    build: tg_bot/
    restart: always

    environment:
        - TG_TOKEN=${TG_TOKEN} # токен telegram бота
        - HOST_URL=${HOST_URL} # URL сервера (если оставить HOST_URL пустым, то бот запустится локально)
        - API_TOKEN=${API_TOKEN}