version: "3"

services:

  frontend_and_nginx:
    build: frontend/
    ports:
      - 0.0.0.0:8080:80


  tg_bot:
    build: tg_bot/
    restart: always
    ports:
      - 0.0.0.0:8081:8081

    environment:
        - TG_TOKEN=${TG_TOKEN} # токен telegram бота
        - HOST_URL=${HOST_URL} # URL сервера (если оставить HOST_URL пустым, то бот запустится локально)
        - API_TOKEN=${API_TOKEN}