version: "3"

services:
  backend:
    build: backend/
    restart: always
    container_name: backend
    volumes:
      - .:/web_django
    depends_on:
      - db

  frontend_and_nginx:
    build: frontend/
    restart: always
    container_name: frontend_and_nginx
    ports:
      - 0.0.0.0:8080:80
    links:
      - backend

db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE} 'db_django'
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql


  tg_bot:
    build: tg_bot/
    restart: always

    environment:
        - TG_TOKEN=${TG_TOKEN} # токен telegram бота
        - HOST_URL=${HOST_URL} # URL сервера (если оставить HOST_URL пустым, то бот запустится локально)
        - API_TOKEN=${API_TOKEN}