# Generated by Django 3.1.2 on 2020-10-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parent_id', models.IntegerField()),
                ('target', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
