# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:       

  Remote-ssh-command:
    name: Remote-ssh-command
    runs-on: ubuntu-latest
    
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
      
        script: |
          if ! [ -d En_group_bot ]; then git clone https://github.com/SiberBit/En_group_bot.git; fi
          cd En_group_bot
          git pull
          ls -ltr
          
          export $(cat En_group_bot/.env.example)
          
          export TG_TOKEN=${{ secrets.DJANGO_SECRET_KEY }}
          export TG_TOKEN=${{ secrets.TG_TOKEN }}
          
          set > En_group_bot/.env
          
          docker-compose build 
          docker-compose up -d
          
          sleep 3
          docker ps -a
          docker image rm $(docker image ls -f dangling=true -q)
