# Generated by Django 3.1.2 on 2020-10-21 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='creation_datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
