# Generated by Django 3.1.2 on 2020-10-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_manager', '0004_departments_organizations'),
        ('question_manager', '0004_chatbot_departments_organizations'),
    ]

    operations = [
    ]
